<div>
    <script src="js/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>


    <?php
    include 'homeSecretaire.php';
    ?>
    <div id="add_data_Modal" class="modal fade" tabindex="-1" role="dialog" style="opacity: 1">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Ajouter un médecin</h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="insert_form" action="ajouterEnseignant.php">

                        <label>Nom</label>
                        <input type="text" name="nom_e" id="nom" class="form-control" />
                        <br/>

                        <label>Prénom</label>
                        <input type="text" name="prenom_e" id="prenom" class="form-control" />
                        <br/>

                        <label>Adresse</label>
                        <textarea name="adresse_e" id="adresse" class="form-control"></textarea>
                        <br/>

                        <label>Grade</label>
                        <input type="text" name="grade_e" id="grade" class="form-control" />
                        <br/>

                        <label>Nom d'utilisateur</label>
                        <input type="text" name="user" id="user" class="form-control"/>
                        <br/>

                        <label>Mot de passe</label>
                        <input type="password" name="password" id="password" class="form-control"/>
                        <br/>
                        <input type="hidden" name="id" id="id" />
                        <input type="submit" name="insert" id="insert" value="Valider" class="btn btn-primary" />

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>

                </div>
            </div>
        </div>
    </div>

    <style>

        .modal-backdrop.in {
            opacity: 0;
           display: none;
        }

    </style>
</div>
<!-- ici on affiche le tableau -->
<div align="center">
    <h2>Liste Enseignants</h2>
</div>
<div align="right">
    <button type="button" class="btn btn-primary" name="ajout" id="ajout" onclick="$('#add_data_Modal').modal('show');">
        <i class="fa fa-plus"></i>Ajouter</button>
</div>
<br/>
<div class="container col-md-10" id="table_medecin">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <caption class="sr-only">Liste des Enseignants.</caption>
        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idENSEIGNANT" role="gridcell" style="display:none">ID</th>
            <th id="nom_e" role="gridcell">Nom</th>
            <th id="prenom_e" role="gridcell">Prénom</th>
            <th id="adresse_e" role="gridcell">Adresse</th>
            <th id="grade_m" role="gridcell">Grade</th>
            <th id="action" role="gridcell">Action</th


        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=plan&go;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM enseigants');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="ids" role="gridcell" style="display:none"><?php echo $donne['idEnseignant'];?></td>
                <td id="nom_e" role="gridcell"><?php echo $donne['nomEns'];?></td>
                <td id="prenom_e" role="gridcell"><?php echo $donne['prenomEns'];?></td>
                <td id="adresse_e" role="gridcell"><?php echo $donne['adresseEns'];?></td>
                <td id="grade_e" role="gridcell"><?php echo $donne['gradeEns'];?></td>

                <td>
<!-- kismeha dik la page ?-->
                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-primary btn-lm dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">

                            <li><input type="button" name="edit" value="Modifier" id="<?php echo $donne["idEnseignant"];?>"
                                       class="btn btn-warning btn-md edit_data btn-block"/></li>


                            <li><input type="button" name="delete" value="Supprimer" id="<?php echo $donne["idEnseignant"];?>"
                                       class="btn btn-danger btn-md delete_data btn-block"/></li>
                        </ul>
                    </div>


                </td>

            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>

<script src='js/jquery.dataTables.js'></script>
<script src='js/dataTables.bootstrap.min.js'></script>

<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->

<script>

    /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

    $(document).ready(function(){


        /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }/*il y'avait 3 pour le double clique et modifier*/
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');
        // $('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');

    });

    //bouton ajouter

    $('#ajout').click(function () {
        $('#insert').val("Valider");
        $('#insert_form')[0].reset();
    });


    /******************** bouton modifier*********************/

    $(document).on('click', '.edit_data', function () {
        var id = $(this).attr("id");
        $.ajax({
            url: "ModifierEnseignant.php",
            method: "POST",
            data: {id: id},
            dataType: "json",
            success: function (data) {
                //remplir les cases avec les anciens données
                $('#nom').val(data.nomEns);
                $('#prenom').val(data.prenomEns);
                $('#adresse').val(data.adresseEns);
                $('#grade').val(data.gradeEns);
                $('#id').val(data.idEseignant);

                $('#insert').val("Modifier");
                $('#add_data_Modal').modal('show');

            }});
    });



    /****Supprimer****/

    $(document).on('click','.delete_data', function(){

        var id=$(this).attr("id");
        if(confirm("êtes-vous sûr de supprimer cet enseignants ?")){

            $.ajax({
                url:'suppEnse.php',
                type: 'POST',
                data:{
                    ids:id
                },
                success: function(result){
                    if(result.trim() == "success")
                        window.location.reload();
                    else alert(result.trim());

                }
            });



        }
    });


</script>







<!--pour afficher les btn delete et edit-->
<script src="js/jquery.tabledit.min.js"></script>
<!--
<script>
    $(document).ready(function(){
        $('#insert_form').on("submit", function(event){
            event.preventDefault();
            if($('#nom').val() == "")
            {
                alert("Name is required");
            }
            else if($('#prenom').val() == '')
            {
                alert("prenom is required");
            }
            else if($('#grade').val() == '')
            {
                alert("grade is required");
            }

            else
            {
                //faire appelle directement à ajouterMedecin.php
                $.ajax({
                    url:"ajouterMedecin.php",
                    method:"POST",
                    data:$('#insert_form').serialize(),
                    beforeSend:function(){
                        $('#insert').val("Inserting");
                    },
                    success:function(data){
                        $('#insert_form')[0].reset();
                        $('#add_data_Modal').modal('hide');
                        $('#table_medecin').html(data);
                    }
                });
            }
        });
    });
</script>




-->






