<div>
    <link href="css/bootstrap.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="homeSecretaire.css"/>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>

    <script src="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"></script>
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <?php
    //include 'homeSecretaire.php';
    ?>
</div>
<br><br>
<!-- la liste patients "table" -->
<div align="center">
    <h2>Liste Etudiants</h2>
</div>
    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered" align="center">
        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idEtudiant" role="gridcell" style="display:none">ID</th>
            <th id="nomEtu" role="gridcell">Nom</th>
            <th id="prenomEtu" role="gridcell">prenom</th>
            <th id="adresseEtu" role="gridcell">Adresse</th>
            <th id="anneeEtu" role="gridcell">annee</th>
            <th id="specialiteEtu" role="gridcell">spec</th>
            <th id="moyenneEtu" role="gridcell">moyenneEtu</th>

        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=plan&go;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM etudiants');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="idEtudiant" role="gridcell" style="display:none"><?php echo $donne['idEtudiant'];?></td>
                <td id="nomEtu" role="gridcell"><?php echo $donne['nomEtu'];?></td>
                <td id="prenomEtu" role="gridcell"><?php echo $donne['prenomEtu'];?></td>
                <td id="adresseEtu" role="gridcell"><?php echo $donne['adresseEtu'];?></td>
                <td id="anneeEtu" role="gridcell"><?php echo $donne['anneeEtu'];?></td>
                <td id="specialiteEtu" role="gridcell"><?php echo $donne['specialiteEtu'];?></td>
                <td id="moyenneEtu" role="gridcell" ><?php echo $donne['moyenneEtu'];?></td>


                <td>

                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-primary btn-lm dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">

                            <li><input type="button" name="edit" value="Modifier" id="<?php echo $donne["idEtudiant"];?>"
                                       class="btn btn-warning btn-md edit_data btn-block"/></li>


                            <li><input type="button" name="delete" value="Supprimer" id="<?php echo $donne["idEtudiant"];?>"
                                       class="btn btn-danger btn-md delete_data btn-block"/></li>
                        </ul>
                    </div>


                </td>

                <td ><a class="btn btn-info" href="details.php?idp=<?php echo $donne['idEtudiant'];?>">Details</a></td>
            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

<!-- pose problème <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>

<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
<script>

    $(document).ready(function(){


        /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }/*il y'avait 3 pour le double clique et modifier*/
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');
        // $('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');

    });

    //bouton ajouter

    $('#ajout').click(function () {
        $('#insert').val("Valider");
        $('#insert_form')[0].reset();
    });


    /******************** bouton modifier*********************/

    $(document).on('click', '.edit_data', function () {
        var id = $(this).attr("id");
        $.ajax({
            url: "modifierMoyenne",
            method: "POST",
            data: {id: id},
            dataType: "json",
            success: function (data) {
                //remplir les cases avec les anciens données
                $('#nom').val(data.nomEtu);
                $('#prenom').val(data.prenomEtu);
                $('#adresseEtu').val(data.);
                $('#adresse').val(data.adresse_p);
                $('#numTel').val(data.numTel_p);
                $('#dateN').val(data.DateNaissance_p);
                $('#dateR').val(data.DateRdv);
                $('#debut').val(data.dateD);
                $('#fin').val(data.dateF);
                $('#nlit').val(data.lit);

                $('#id').val(data.idPATIENT);

                $('#insert').val("Modifier");
                $('#add_data_Modal').modal('show');


            }

        });
    });


    /*********************** pour le bouton ajouter ******************/
    /*
        $('#insert_form').on("submit", function (event) {
            event.preventDefault();
             if ($('#nom').val() == "") {          // si le champs nom n'est pas vide

                 alert("Le nom est obligatoire!");  //ç n marche pas .. j v essayer les sweet alert!
             }
             else {
            $.ajax({
                url: "ajouterPatient.php",
                method: "POST",
                data: $('#insert_form').serialize(),
                beforeSend: function () {
                    $('#insert').val("Valider");
                },
                success: function (data) {
                    $('#insert_form')[0].reset();
                    $('#add_data_Modal').modal('hide');
                    $('#table_patient').html(data);
                }
            });
            //}
        });
        */

    /******************************* SUPPRIMER Patient********************/


    $(document).on('click', '.delete_data', function(){
        var id = $(this).attr("id");
        if(confirm("êtes vous sûr de supprimer ce patient?"))
        {
            $.ajax({
                url:"SupprimerPatient.php",
                method:"POST",
                data:{id:id},
                success:function(data){
                    $('#table_patient').html('<div class="alert alert-success">'+data+'</div>');
                    $('#autoGeneratedID').DataTable().destroy();
                    window.location.reload();

                }
            });
            setInterval(function(){
                $('#table_patient').html('');
            }, 5000);
        }
    });



</script>
<script>$(document).ready( function () {
        $('#myTable').DataTable();
    } );</script>


